esphome:
  name: z4-relay-v1

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    password: !secret ap_password

ota:
  platform: esphome
  password: !secret ota_password_v1

udp:

switch:
- platform: gpio
  pin: GPIO23
  id: accenture_laptop_charger
  restore_mode: RESTORE_DEFAULT_ON
- platform: gpio
  pin: GPIO22
  id: msi_laptop_charger
  restore_mode: RESTORE_DEFAULT_ON
- platform: gpio
  pin: GPIO21
  id: mosquito_killer
  restore_mode: RESTORE_DEFAULT_ON
- platform: gpio
  pin: GPIO19
  id: jci_laptop_charger
  restore_mode: RESTORE_DEFAULT_ON

binary_sensor:
- platform: udp
  provider: z4-relay-v2
  id: accenture_laptop_charger_sensor
  on_press:
    switch.turn_on: accenture_laptop_charger
  on_release:
    switch.turn_off: accenture_laptop_charger
- platform: udp
  provider: z4-relay-v2
  id: msi_laptop_charger_sensor
  on_press:
    switch.turn_on: msi_laptop_charger
  on_release:
    switch.turn_off: msi_laptop_charger
- platform: udp
  provider: z4-relay-v2
  id: mosquito_killer_sensor
  on_press:
    switch.turn_on: mosquito_killer
  on_release:
    switch.turn_off: mosquito_killer
- platform: udp
  provider: z4-relay-v2
  id: jci_laptop_charger_sensor
  on_press:
    switch.turn_on: jci_laptop_charger
  on_release:
    switch.turn_off: jci_laptop_charger
