esphome:
  name: z4-relay-v1
  friendly_name: "Z4 Relay v1"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    password: !secret ap_password

ota:
  platform: esphome
  password: !secret ota_password_v1

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  log: false
  ota: false
  version: 3
  sorting_groups:
    - id: sorting_group_charger
      name: Laptop Chargers
      sorting_weight: 1
    - id: sorting_group_misc
      name: Mosquito Killer
      sorting_weight: 2

switch:
  - platform: gpio
    pin: GPIO23
    name: "Accenture Laptop Charger"
    restore_mode: RESTORE_DEFAULT_ON
    web_server:
      sorting_group_id: sorting_group_charger
      sorting_weight: 2
  - platform: gpio
    pin: GPIO22
    name: "MSI Laptop Charger"
    restore_mode: RESTORE_DEFAULT_ON
    web_server:
      sorting_group_id: sorting_group_charger
      sorting_weight: 3
  - platform: gpio
    pin: GPIO21
    name: "Mosquito Killer"
    restore_mode: RESTORE_DEFAULT_ON
    web_server:
      sorting_group_id: sorting_group_misc
  - platform: gpio
    pin: GPIO19
    name: "JCI Laptop Charger"
    restore_mode: RESTORE_DEFAULT_ON
    web_server:
      sorting_group_id: sorting_group_charger
      sorting_weight: 1
