esphome:
  name: z4-relay-v2
  friendly_name: "Z4 Relay v2"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    password: !secret ap_password

captive_portal:

logger:

ota:
  platform: esphome
  password: !secret ota_password_v2

web_server:
  port: 80
  ota: false
  version: 3
  sorting_groups:
  - id: sorting_group_lights
    name: Lights
    sorting_weight: 1
  - id: sorting_group_chargers
    name: Laptop Chargers
    sorting_weight: 2
  - id: sorting_group_fans
    name: Fans
    sorting_weight: 3
  - id: sorting_group_misc
    name: Misc
    sorting_weight: 4
  - id: sorting_group_sensors
    name: Sensors
    sorting_weight: 5

udp:
  binary_sensors:
  - accenture_laptop_charger_sensor
  - msi_laptop_charger_sensor
  - mosquito_killer_sensor
  - jci_laptop_charger_sensor

switch:
- platform: gpio
  pin:
    number: GPIO5
    inverted: True
  name: "Office Light"
  id: office_light
  icon: mdi:lightbulb
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_lights
    sorting_weight: 1
- platform: gpio
  pin:
    number: GPIO17
    inverted: True
  name: "Workbench Light"
  id: workbench_light
  icon: mdi:lightbulb
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_lights
    sorting_weight: 2
- platform: gpio
  pin:
    number: GPIO16
    inverted: True
  name: "Bathroom Light"
  id: bathroom_light
  icon: mdi:lightbulb
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_lights
    sorting_weight: 3
- platform: gpio
  pin:
    number: GPIO4
    inverted: True
  name: "Wall Socket"
  id: wall_socket
  icon: mdi:power-socket-uk
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_misc
    sorting_weight: 1

- platform: gpio
  pin:
    number: GPIO19
    inverted: True
  id: fan_speed_1
  restore_mode: RESTORE_DEFAULT_OFF
- platform: gpio
  pin:
    number: GPIO21
    inverted: True
  id: fan_speed_2
  restore_mode: RESTORE_DEFAULT_OFF
- platform: gpio
  pin:
    number: GPIO22
    inverted: True
  id: fan_speed_3
  restore_mode: RESTORE_DEFAULT_OFF
- platform: gpio
  pin:
    number: GPIO23
    inverted: True
  id: fan_speed_4
  restore_mode: RESTORE_DEFAULT_OFF

- platform: template
  name: "Office Fan"
  id: office_fan
  icon: mdi:fan
  optimistic: true
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_fans
    sorting_weight: 1
  on_turn_on:
    script.execute: change_fan_speed
  on_turn_off:
    script.execute: change_fan_speed

- platform: template
  name: "Accenture Laptop Charger"
  id: accenture_laptop_charger
  icon: mdi:laptop
  optimistic: true
  restore_mode: RESTORE_DEFAULT_ON
  web_server:
    sorting_group_id: sorting_group_chargers
    sorting_weight: 2
- platform: template
  name: "MSI Laptop Charger"
  id: msi_laptop_charger
  icon: mdi:laptop-account
  optimistic: true
  restore_mode: RESTORE_DEFAULT_ON
  web_server:
    sorting_group_id: sorting_group_chargers
    sorting_weight: 3
- platform: template
  name: "Mosquito Killer"
  id: mosquito_killer
  icon: mdi:bug
  optimistic: true
  restore_mode: RESTORE_DEFAULT_ON
  web_server:
    sorting_group_id: sorting_group_misc
    sorting_weight: 2
  on_turn_on: 
    - delay: 30min
    - switch.turn_off: mosquito_killer
- platform: template
  name: "JCI Laptop Charger"
  id: jci_laptop_charger
  icon: mdi:laptop
  optimistic: true
  restore_mode: RESTORE_DEFAULT_ON
  web_server:
    sorting_group_id: sorting_group_chargers
    sorting_weight: 1

- platform: template
  name: "Enable Motion Sensor"
  id: enable_motion_sensor
  icon: mdi:walk
  optimistic: true
  restore_mode: RESTORE_DEFAULT_ON
  web_server:
    sorting_group_id: sorting_group_sensors
    sorting_weight: 3
  on_turn_off: 
    script.stop: turn_off_led_timer

sensor:
- platform: dht
  pin: GPIO18
  temperature:
    name: "Office Temperature"
    icon: mdi:thermometer
    filters:
    - filter_out: nan
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 1
  humidity:
    name: "Office Humidity"
    icon: mdi:water-percent
    filters:
    - filter_out: nan
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 2
  model: DHT11
  update_interval: 60s

binary_sensor:
- platform: gpio
  pin: GPIO26
  id: motion_sensor
  device_class: motion
  filters:
  - lambda: |-
      if (id(enable_motion_sensor).state) {
        return x;
      } else {
        return {};
      }
  on_press:
    if:
      condition:
        switch.is_off: office_light
      then:
      - switch.turn_on: office_light
      - script.stop: turn_off_led_timer
      else:
      - script.stop: turn_off_led_timer
  on_release:
    if:
      condition:
        script.is_running: turn_off_led_timer
      else:
      - script.execute: turn_off_led_timer

- platform: gpio
  pin:
    number: GPIO34
    mode:
      input: True
      # pullup: True
    inverted: True
  id: office_light_switch
  filters:
  - delayed_on_off: 100ms
  on_press:
    switch.turn_on: office_light
  on_release:
    switch.turn_off: office_light
- platform: gpio
  pin:
    number: GPIO35
    mode:
      input: True
      # pullup: True
    inverted: True
  id: workbench_light_switch
  filters:
  - delayed_on_off: 100ms
  on_press:
    switch.turn_on: workbench_light
  on_release:
    switch.turn_off: workbench_light
- platform: gpio
  pin:
    number: GPIO32
    mode:
      input: True
      pullup: True
    inverted: True
  id: bathroom_light_switch
  filters:
  - delayed_on_off: 100ms
  on_press:
    switch.turn_on: bathroom_light
  on_release:
    switch.turn_off: bathroom_light
- platform: gpio
  pin:
    number: GPIO33
    mode:
      input: True
      pullup: True
    inverted: True
  id: socket_switch
  filters:
  - delayed_on_off: 100ms
  on_press:
    switch.turn_on: wall_socket
  on_release:
    switch.turn_off: wall_socket

- platform: gpio
  pin:
    number: GPIO25
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_switch
  filters:
  - delayed_on_off: 100ms
  on_press:
    switch.turn_on: office_fan
  on_release:
    switch.turn_off: office_fan

- platform: gpio
  pin:
    number: GPIO27
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_speed_rotary_1
  filters:
  - delayed_on_off: 100ms
  on_press:
    number.set:
      id: fan_speed
      value: 1
  on_release:
    number.set:
      id: fan_speed
      value: 0
- platform: gpio
  pin:
    number: GPIO14
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_speed_rotary_2
  filters:
  - delayed_on_off: 100ms
  on_press:
    number.set:
      id: fan_speed
      value: 2
- platform: gpio
  pin:
    number: GPIO12
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_speed_rotary_3
  filters:
  - delayed_on_off: 100ms
  on_press:
    number.set:
      id: fan_speed
      value: 3
- platform: gpio
  pin:
    number: GPIO13
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_speed_rotary_4
  filters:
  - delayed_on_off: 100ms
  on_press:
    number.set:
      id: fan_speed
      value: 4
  on_release:
    number.set:
      id: fan_speed
      value: 0

- platform: template
  id: accenture_laptop_charger_sensor
  lambda: return id(accenture_laptop_charger).state;
- platform: template
  id: msi_laptop_charger_sensor
  lambda: return id(msi_laptop_charger).state;
- platform: template
  id: mosquito_killer_sensor
  lambda: return id(mosquito_killer).state;
- platform: template
  id: jci_laptop_charger_sensor
  lambda: return id(jci_laptop_charger).state;

script:
- id: turn_off_led_timer
  then:
    if:
      condition:
        switch.is_on: office_light
      then:
      - delay: 120s
      - switch.turn_off: office_light
- id: change_fan_speed
  then:
  - lambda: |-
      if (id(office_fan).state) {
        if (id(fan_speed).state == 0) {
          id(fan_speed_1).turn_off();
          id(fan_speed_2).turn_off();
          id(fan_speed_3).turn_off();
          id(fan_speed_4).turn_off();
        } else if (id(fan_speed).state == 1) {
          id(fan_speed_2).turn_off();
          id(fan_speed_3).turn_off();
          id(fan_speed_4).turn_off();
          id(fan_speed_1).turn_on();
        } else if (id(fan_speed).state == 2) {
          id(fan_speed_1).turn_off();
          id(fan_speed_3).turn_off();
          id(fan_speed_4).turn_off();
          id(fan_speed_2).turn_on();
        } else if (id(fan_speed).state == 3) {
          id(fan_speed_1).turn_off();
          id(fan_speed_4).turn_off();
          id(fan_speed_2).turn_on();
          id(fan_speed_3).turn_on();
        } else if (id(fan_speed).state == 4) {
          id(fan_speed_1).turn_off();
          id(fan_speed_2).turn_off();
          id(fan_speed_3).turn_off();
          id(fan_speed_4).turn_on();
        }
      } else {
        id(fan_speed_1).turn_off();
        id(fan_speed_2).turn_off();
        id(fan_speed_3).turn_off();
        id(fan_speed_4).turn_off();
      }

number:
- platform: template
  name: "Office Fan Speed"
  id: fan_speed
  icon: mdi:fan-clock
  min_value: 0
  max_value: 4
  step: 1
  optimistic: true
  restore_value: True
  device_class: speed
  mode: SLIDER
  web_server:
    sorting_group_id: sorting_group_fans
    sorting_weight: 2
  on_value:
    script.execute: change_fan_speed

time:
- platform: sntp
  id: sntp_time
  timezone: Asia/Kolkata
  on_time: 
  - hours: 6
    minutes: 0
    seconds: 0
    then:
    - switch.turn_on: enable_motion_sensor
  - hours: 10
    minutes: 0
    seconds: 0
    then:
    - switch.turn_on: wall_socket
  - days_of_week: MON-FRI
    hours: 10
    minutes: 0
    seconds: 0
    then:
    - switch.turn_on: jci_laptop_charger
    - switch.turn_on: accenture_laptop_charger
  - days_of_week: SAT-SUN
    hours: 10
    minutes: 0
    seconds: 0
    then:
    - switch.turn_on: msi_laptop_charger
  - hours: 19
    minutes: 0
    seconds: 0
    then:
    - switch.turn_on: mosquito_killer
    - switch.turn_off: jci_laptop_charger
    - switch.turn_off: accenture_laptop_charger
  - hours: 23
    minutes: 0
    seconds: 0
    then:
    - switch.turn_off: enable_motion_sensor

# Pin mapping

# GPIO19 - D19 - Fan Speed 1
# GPIO21 - D21 - Fan Speed 2
# GPIO22 - D22 - Fan Speed 3
# GPIO23 - D23 - Fan Speed 4

# GPIO18 - D18 - DHT11

# GPIO5 - D5 - Office Light
# GPIO17 - TX2 - Workbench Light
# GPIO16 - RX2 - Bathroom Light
# GPIO4 - D4 - Wall Socket

# GPIO34 - D34 - Office Light Switch
# GPIO35 - D35 - Workbench Light Switch
# GPIO32 - D32 - Bathroom Light Switch
# GPIO33 - D33 - Wall Socket Switch

# GPIO25 - D25 - Fan Switch

# GPIO26 - D26 - Motion Sensor

# GPIO27 - D27 - Fan Speed Rotary 1
# GPIO14 - D14 - Fan Speed Rotary 2
# GPIO12 - D12 - Fan Speed Rotary 3
# GPIO13 - D13 - Fan Speed Rotary 4
