esphome:
  name: z4-relay-v2
  friendly_name: "Z4 Relay v2"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    password: !secret ap_password

captive_portal:

logger:

ota:
  platform: esphome
  password: !secret ota_password_v2

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  ota: false
  version: 3

switch:
  - platform: gpio
    pin: GPIO2
    name: "USER LED"
    id: user_led
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: dht
    pin: GPIO18
    temperature:
      name: "Office Temperature"
      filters:
        - filter_out: nan
    humidity:
      name: "Office Humidity"
      filters:
        - filter_out: nan
    model: DHT11
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO25
    name: "Office Door"
    device_class: motion
    on_press:
      then:
        if:
          condition:
            switch.is_off: user_led
          then:
            - switch.turn_on: user_led
            - script.stop: turn_off_led_timer
          else:
            - script.stop: turn_off_led_timer
    on_release:
      then:
        if:
          condition:
            script.is_running: turn_off_led_timer
          else:
            - script.execute: turn_off_led_timer

script:
  - id: turn_off_led_timer
    then:
      if:
        condition:
          switch.is_on: user_led
        then:
          - delay: 10s
          - switch.turn_off: user_led
