esphome:
  name: z4-relay-v2
  friendly_name: "Z4 Relay v2"

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    password: !secret ap_password

captive_portal:

logger:

ota:
  platform: esphome
  password: !secret ota_password_v2

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
  ota: false
  version: 3
  sorting_groups:
  - id: sorting_group_lights
    name: Lights
    sorting_weight: 1
  - id: sorting_group_fans
    name: Fans
    sorting_weight: 2
  - id: sorting_group_misc
    name: Misc
    sorting_weight: 3
  - id: sorting_group_sensors
    name: Sensors
    sorting_weight: 4

switch:
- platform: gpio
  pin:
    number: GPIO5
    inverted: True
  name: "Office Light"
  id: office_light
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_lights
    sorting_weight: 1
- platform: gpio
  pin:
    number: GPIO17
    inverted: True
  name: "Workbench Light"
  id: workbench_light
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_lights
    sorting_weight: 2
- platform: gpio
  pin:
    number: GPIO16
    inverted: True
  name: "Bathroom Light"
  id: bathroom_light
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_lights
    sorting_weight: 3
- platform: gpio
  pin:
    number: GPIO4
    inverted: True
  name: "Socket"
  id: wall_socket
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_misc
- platform: gpio
  pin:
    number: GPIO23
    inverted: True
  id: fan_speed_1
  restore_mode: RESTORE_DEFAULT_OFF
- platform: gpio
  pin:
    number: GPIO22
    inverted: True
  id: fan_speed_2
  restore_mode: RESTORE_DEFAULT_OFF
- platform: gpio
  pin:
    number: GPIO21
    inverted: True
  id: fan_speed_3
  restore_mode: RESTORE_DEFAULT_OFF
- platform: gpio
  pin:
    number: GPIO19
    inverted: True
  id: fan_speed_4
  restore_mode: RESTORE_DEFAULT_OFF
- platform: template
  name: "Office Fan Switch"
  id: office_fan
  optimistic: true
  restore_mode: RESTORE_DEFAULT_OFF
  web_server:
    sorting_group_id: sorting_group_fans
    sorting_weight: 1
  on_turn_on:
    then:
    - if:
        condition:
          lambda: return (id(fan_speed).state == 0);
        then:
        - number.set:
            id: fan_speed
            value: 4
        else:
        - script.execute: change_fan_speed
  on_turn_off:
    then:
    - script.execute: change_fan_speed

sensor:
- platform: dht
  pin: GPIO18
  temperature:
    name: "Office Temperature"
    filters:
    - filter_out: nan
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 1
  humidity:
    name: "Office Humidity"
    filters:
    - filter_out: nan
    web_server:
      sorting_group_id: sorting_group_sensors
      sorting_weight: 2
  model: DHT11
  update_interval: 60s

binary_sensor:
- platform: gpio
  pin: GPIO26
  id: motion_sensor
  device_class: motion
  on_press:
    then:
      if:
        condition:
          switch.is_off: office_light
        then:
        - switch.turn_on: office_light
        - script.stop: turn_off_led_timer
        else:
        - script.stop: turn_off_led_timer
  on_release:
    then:
      if:
        condition:
          script.is_running: turn_off_led_timer
        else:
        - script.execute: turn_off_led_timer
- platform: gpio
  pin:
    number: GPIO34
    mode:
      input: True
      # pullup: True
    inverted: True
  id: office_light_switch
  on_press:
    then:
    - switch.turn_on: office_light
  on_release:
    then:
    - switch.turn_off: office_light
- platform: gpio
  pin:
    number: GPIO35
    mode:
      input: True
      # pullup: True
    inverted: True
  id: workbench_light_switch
  on_press:
    then:
    - switch.turn_on: workbench_light
  on_release:
    then:
    - switch.turn_off: workbench_light
- platform: gpio
  pin:
    number: GPIO32
    mode:
      input: True
      pullup: True
    inverted: True
  id: bathroom_light_switch
  on_press:
    then:
    - switch.turn_on: bathroom_light
  on_release:
    then:
    - switch.turn_off: bathroom_light
- platform: gpio
  pin:
    number: GPIO33
    mode:
      input: True
      pullup: True
    inverted: True
  id: socket_switch
  on_press:
    then:
    - switch.turn_on: wall_socket
  on_release:
    then:
    - switch.turn_off: wall_socket
- platform: gpio
  pin:
    number: GPIO25
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_switch
  filters:
  - delayed_on_off: 100ms
  on_press:
    then:
    - switch.turn_on: office_fan
  on_release:
    then:
    - switch.turn_off: office_fan

- platform: gpio
  pin:
    number: GPIO27
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_speed_rotary_1
  filters:
  - delayed_on_off: 100ms
  on_press:
    then:
    - number.set:
        id: fan_speed
        value: 1
  on_release:
    then:
    - number.set:
        id: fan_speed
        value: 0
- platform: gpio
  pin:
    number: GPIO14
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_speed_rotary_2
  filters:
  - delayed_on_off: 100ms
  on_press:
    then:
    - number.set:
        id: fan_speed
        value: 2
- platform: gpio
  pin:
    number: GPIO12
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_speed_rotary_3
  filters:
  - delayed_on_off: 100ms
  on_press:
    then:
    - number.set:
        id: fan_speed
        value: 3
- platform: gpio
  pin:
    number: GPIO13
    mode:
      input: True
      pullup: True
    inverted: True
  id: fan_speed_rotary_4
  filters:
  - delayed_on_off: 100ms
  on_press:
    then:
    - number.set:
        id: fan_speed
        value: 4
  on_release:
    then:
    - number.set:
        id: fan_speed
        value: 0

script:
- id: turn_off_led_timer
  then:
    if:
      condition:
        switch.is_on: office_light
      then:
      - delay: 120s
      - switch.turn_off: office_light
- id: change_fan_speed
  then: 
    - lambda: |-
        if (id(office_fan).state) {
          if (id(fan_speed).state == 0) {
            id(fan_speed_1).turn_off();
            id(fan_speed_2).turn_off();
            id(fan_speed_3).turn_off();
            id(fan_speed_4).turn_off();
          } else if (id(fan_speed).state == 1) {
            id(fan_speed_2).turn_off();
            id(fan_speed_3).turn_off();
            id(fan_speed_4).turn_off();
            id(fan_speed_1).turn_on();
          } else if (id(fan_speed).state == 2) {
            id(fan_speed_1).turn_off();
            id(fan_speed_3).turn_off();
            id(fan_speed_4).turn_off();
            id(fan_speed_2).turn_on();
          } else if (id(fan_speed).state == 3) {
            id(fan_speed_1).turn_off();
            id(fan_speed_4).turn_off();
            id(fan_speed_2).turn_on();
            id(fan_speed_3).turn_on();
          } else if (id(fan_speed).state == 4) {
            id(fan_speed_1).turn_off();
            id(fan_speed_2).turn_off();
            id(fan_speed_3).turn_off();
            id(fan_speed_4).turn_on();
          }
        } else {
          id(fan_speed_1).turn_off();
          id(fan_speed_2).turn_off();
          id(fan_speed_3).turn_off();
          id(fan_speed_4).turn_off();
        }

number:
- platform: template
  name: "Office Fan Speed"
  id: fan_speed
  min_value: 0
  max_value: 4
  step: 1
  optimistic: true
  restore_value: True
  device_class: speed
  mode: SLIDER
  web_server:
    sorting_group_id: sorting_group_fans
    sorting_weight: 2
  on_value:
    then:
    - script.execute: change_fan_speed